name: Frontend Tests

on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    
      - uses: actions/checkout@v2
      
      - name: setup
        run: |
          rm /var/lib/apt/lists/lock
          rm /var/cache/apt/archives/lock
          rm /var/lib/dpkg/lock*
          npm install
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          apt-get update
          apt-get install google-chrome-stable
          apt-get --only-upgrade install google-chrome-stable
          echo "google-chrome --version"
          npm install -g webdriver-manager
          webdriver-manager update
          webdriver-manager start &
          
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    needs: setup
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: run-tests
        run: |
          npm run test1-headless;
    
    
    
        
