name: Frontend Tests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: setup
        run: |
          pwd
          sudo apt-get --only-upgrade install google-chrome-stable
          echo node version: `node --version`
          echo npm version: `npm --version`
          echo google chrome browser version: `google-chrome --version`
          npm install
          npm run clean
          npm install -g webdriver-manager
          webdriver-manager update --versions.chrome=107.0.5304.121
          webdriver-manager start --versions.chrome=107.0.5304.121 &
          
      - name: tests1
        run: |
          pwd
          npm --version
          sleep 20 && npm run test1-headless;
          
      - name: tests2
        run: |
          pwd
          npm --version
          sleep 20 && npm run test2-headless;
    
