name: Frontend Tests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          # installing dependencies
          npm install
          # installing chrome browser
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          apt-get update
          apt-get install google-chrome-stable
          apt-get --only-upgrade install google-chrome-stable
          echo "google-chrome --version"
          
      - name: tests-set-1
        run: |
          npm run test1-headless;
        
