name: Frontend Tests GHP branch

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: setup
        run: |
          pwd
          sudo apt-get --only-upgrade install google-chrome-stable
          echo node version: `node --version`
          echo npm version: `npm --version`
          echo google chrome browser version: `google-chrome --version`
          npm install
          npm run clean
          npm install -g webdriver-manager
          webdriver-manager update --versions.chrome=107.0.5304.121
          webdriver-manager start --versions.chrome=107.0.5304.121 &
          
      - name: tests1
        run: |
          pwd
          npm --version
          sleep 20 && npm run test1-headless;
          
      - name: tests2
        run: |
          pwd
          npm --version
          sleep 20 && npm run test2-headless;
          
      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: test-reports
          path: test-reports
          
      - name: Move Report Artifacts
        run: find report/**/ -type f \( -name "*.xml" -o -name "*.png" \) -print0 | xargs -0 -I {} mv {} report/ghp_test_reports
        
      - name: Allure Report action from marketplace
        if: steps.check-artifacts-files.outputs.has_files == 'true'
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: report
          allure_report: ghp_test_reports
          gh_pages: test-reports
          allure_history: allure-history
          subfolder: ghp_test_reports
          
      - name: Deploy report to Github Pages
        if: steps.check-artifacts-files.outputs.has_files == 'true'
        uses: peaceiris/actions-gh-pages@v2
        env:
#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: test-reports
          PUBLISH_DIR: allure-history
          DESTINATION_DIR: ghp_test_reports

      - name: Report Link
        if: steps.check-artifacts-files.outputs.has_files == 'true'
        run: echo "https://murtaza9teen91.github.io/codecept_webdriver_framework/ghp_test_reports/${{ github.run_number }}"
    
