name: Just Tests

on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: setup
        run: |
          pwd
          npm --version
          npm install
          npm install --save-dev webdriverio@^6.12.1
          npm install -g webdriver-manager
          webdriver-manager update
          webdriver-manager start &
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          apt-get update
          apt-get install google-chrome-stable
          apt-get --only-upgrade install google-chrome-stable
          sleep 20 && npm run test1-headless;
          
  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    
      - uses: actions/checkout@v2
      
      - name: run-tests
        run: |
          npm run test1-headless;
    
