name: Just Tests

on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: setup
        run: |
          pwd
          npm --version
          npm install
          
  tests:
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: run-tests
        run: |
          npm run test1-headless;
    
